// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: xqecz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "image" | "video"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailRequest) Reset() {
	*x = ThumbnailRequest{}
	mi := &file_xqecz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailRequest) ProtoMessage() {}

func (x *ThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{0}
}

func (x *ThumbnailRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ThumbnailRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThumbPath     string                 `protobuf:"bytes,1,opt,name=thumb_path,json=thumbPath,proto3" json:"thumb_path,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailResponse) Reset() {
	*x = ThumbnailResponse{}
	mi := &file_xqecz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailResponse) ProtoMessage() {}

func (x *ThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailResponse.ProtoReflect.Descriptor instead.
func (*ThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{1}
}

func (x *ThumbnailResponse) GetThumbPath() string {
	if x != nil {
		return x.ThumbPath
	}
	return ""
}

func (x *ThumbnailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ThumbnailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressRequest) Reset() {
	*x = CompressRequest{}
	mi := &file_xqecz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressRequest) ProtoMessage() {}

func (x *CompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressRequest.ProtoReflect.Descriptor instead.
func (*CompressRequest) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{2}
}

func (x *CompressRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type CompressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompressedPath string                 `protobuf:"bytes,1,opt,name=compressed_path,json=compressedPath,proto3" json:"compressed_path,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompressResponse) Reset() {
	*x = CompressResponse{}
	mi := &file_xqecz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressResponse) ProtoMessage() {}

func (x *CompressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressResponse.ProtoReflect.Descriptor instead.
func (*CompressResponse) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{3}
}

func (x *CompressResponse) GetCompressedPath() string {
	if x != nil {
		return x.CompressedPath
	}
	return ""
}

func (x *CompressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UploadToS3Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadToS3Request) Reset() {
	*x = UploadToS3Request{}
	mi := &file_xqecz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadToS3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadToS3Request) ProtoMessage() {}

func (x *UploadToS3Request) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadToS3Request.ProtoReflect.Descriptor instead.
func (*UploadToS3Request) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{4}
}

func (x *UploadToS3Request) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadToS3Request) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadToS3Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CdnUrl        string                 `protobuf:"bytes,1,opt,name=cdn_url,json=cdnUrl,proto3" json:"cdn_url,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadToS3Response) Reset() {
	*x = UploadToS3Response{}
	mi := &file_xqecz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadToS3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadToS3Response) ProtoMessage() {}

func (x *UploadToS3Response) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadToS3Response.ProtoReflect.Descriptor instead.
func (*UploadToS3Response) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{5}
}

func (x *UploadToS3Response) GetCdnUrl() string {
	if x != nil {
		return x.CdnUrl
	}
	return ""
}

func (x *UploadToS3Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadToS3Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LinkPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkPreviewRequest) Reset() {
	*x = LinkPreviewRequest{}
	mi := &file_xqecz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkPreviewRequest) ProtoMessage() {}

func (x *LinkPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkPreviewRequest.ProtoReflect.Descriptor instead.
func (*LinkPreviewRequest) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{6}
}

func (x *LinkPreviewRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LinkPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkPreviewResponse) Reset() {
	*x = LinkPreviewResponse{}
	mi := &file_xqecz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkPreviewResponse) ProtoMessage() {}

func (x *LinkPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkPreviewResponse.ProtoReflect.Descriptor instead.
func (*LinkPreviewResponse) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{7}
}

func (x *LinkPreviewResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LinkPreviewResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *LinkPreviewResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LinkPreviewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LinkPreviewResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 推荐输入：由 NestJS 从 MySQL 读取后通过 gRPC 传入。
type RecommendItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     uint64                 `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,2,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"` // 内容创建时间（Unix 秒）
	ViewCount     uint64                 `protobuf:"varint,3,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`               // 浏览量信号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendItem) Reset() {
	*x = RecommendItem{}
	mi := &file_xqecz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendItem) ProtoMessage() {}

func (x *RecommendItem) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendItem.ProtoReflect.Descriptor instead.
func (*RecommendItem) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{8}
}

func (x *RecommendItem) GetContentId() uint64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *RecommendItem) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *RecommendItem) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

// 推荐输出：worker 计算出的评分，返回给 NestJS 由其写入 Redis。
type ScoredItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     uint64                 `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredItem) Reset() {
	*x = ScoredItem{}
	mi := &file_xqecz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredItem) ProtoMessage() {}

func (x *ScoredItem) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredItem.ProtoReflect.Descriptor instead.
func (*ScoredItem) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{9}
}

func (x *ScoredItem) GetContentId() uint64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *ScoredItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RefreshRecommendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NestJS 提供的内容数据（推荐算法需要的输入）
	Items         []*RecommendItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRecommendRequest) Reset() {
	*x = RefreshRecommendRequest{}
	mi := &file_xqecz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRecommendRequest) ProtoMessage() {}

func (x *RefreshRecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRecommendRequest.ProtoReflect.Descriptor instead.
func (*RefreshRecommendRequest) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshRecommendRequest) GetItems() []*RecommendItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RefreshRecommendResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// 计算完成的评分列表，交由 NestJS 写入 Redis ZSet（recommend:hot）。
	Results       []*ScoredItem `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRecommendResponse) Reset() {
	*x = RefreshRecommendResponse{}
	mi := &file_xqecz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRecommendResponse) ProtoMessage() {}

func (x *RefreshRecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRecommendResponse.ProtoReflect.Descriptor instead.
func (*RefreshRecommendResponse) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshRecommendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshRecommendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RefreshRecommendResponse) GetResults() []*ScoredItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_xqecz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{12}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_xqecz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xqecz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_xqecz_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_xqecz_proto protoreflect.FileDescriptor

const file_xqecz_proto_rawDesc = "" +
	"\n" +
	"\vxqecz.proto\x12\x05xqecz\"R\n" +
	"\x10ThumbnailRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"b\n" +
	"\x11ThumbnailResponse\x12\x1d\n" +
	"\n" +
	"thumb_path\x18\x01 \x01(\tR\tthumbPath\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\".\n" +
	"\x0fCompressRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"k\n" +
	"\x10CompressResponse\x12'\n" +
	"\x0fcompressed_path\x18\x01 \x01(\tR\x0ecompressedPath\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"S\n" +
	"\x11UploadToS3Request\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"]\n" +
	"\x12UploadToS3Response\x12\x17\n" +
	"\acdn_url\x18\x01 \x01(\tR\x06cdnUrl\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"&\n" +
	"\x12LinkPreviewRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8d\x01\n" +
	"\x13LinkPreviewResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"u\n" +
	"\rRecommendItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x04R\tcontentId\x12&\n" +
	"\x0fcreated_at_unix\x18\x02 \x01(\x03R\rcreatedAtUnix\x12\x1d\n" +
	"\n" +
	"view_count\x18\x03 \x01(\x04R\tviewCount\"A\n" +
	"\n" +
	"ScoredItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x04R\tcontentId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"E\n" +
	"\x17RefreshRecommendRequest\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.xqecz.RecommendItemR\x05items\"w\n" +
	"\x18RefreshRecommendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\aresults\x18\x03 \x03(\v2\x11.xqecz.ScoredItemR\aresults\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xb3\x03\n" +
	"\rWorkerService\x125\n" +
	"\x06Health\x12\x14.xqecz.HealthRequest\x1a\x15.xqecz.HealthResponse\x12F\n" +
	"\x11GenerateThumbnail\x12\x17.xqecz.ThumbnailRequest\x1a\x18.xqecz.ThumbnailResponse\x12@\n" +
	"\rCompressImage\x12\x16.xqecz.CompressRequest\x1a\x17.xqecz.CompressResponse\x12A\n" +
	"\n" +
	"UploadToS3\x12\x18.xqecz.UploadToS3Request\x1a\x19.xqecz.UploadToS3Response\x12I\n" +
	"\x10FetchLinkPreview\x12\x19.xqecz.LinkPreviewRequest\x1a\x1a.xqecz.LinkPreviewResponse\x12S\n" +
	"\x10RefreshRecommend\x12\x1e.xqecz.RefreshRecommendRequest\x1a\x1f.xqecz.RefreshRecommendResponseB\x14Z\x12xqecz-worker/protob\x06proto3"

var (
	file_xqecz_proto_rawDescOnce sync.Once
	file_xqecz_proto_rawDescData []byte
)

func file_xqecz_proto_rawDescGZIP() []byte {
	file_xqecz_proto_rawDescOnce.Do(func() {
		file_xqecz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xqecz_proto_rawDesc), len(file_xqecz_proto_rawDesc)))
	})
	return file_xqecz_proto_rawDescData
}

var file_xqecz_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_xqecz_proto_goTypes = []any{
	(*ThumbnailRequest)(nil),         // 0: xqecz.ThumbnailRequest
	(*ThumbnailResponse)(nil),        // 1: xqecz.ThumbnailResponse
	(*CompressRequest)(nil),          // 2: xqecz.CompressRequest
	(*CompressResponse)(nil),         // 3: xqecz.CompressResponse
	(*UploadToS3Request)(nil),        // 4: xqecz.UploadToS3Request
	(*UploadToS3Response)(nil),       // 5: xqecz.UploadToS3Response
	(*LinkPreviewRequest)(nil),       // 6: xqecz.LinkPreviewRequest
	(*LinkPreviewResponse)(nil),      // 7: xqecz.LinkPreviewResponse
	(*RecommendItem)(nil),            // 8: xqecz.RecommendItem
	(*ScoredItem)(nil),               // 9: xqecz.ScoredItem
	(*RefreshRecommendRequest)(nil),  // 10: xqecz.RefreshRecommendRequest
	(*RefreshRecommendResponse)(nil), // 11: xqecz.RefreshRecommendResponse
	(*HealthRequest)(nil),            // 12: xqecz.HealthRequest
	(*HealthResponse)(nil),           // 13: xqecz.HealthResponse
}
var file_xqecz_proto_depIdxs = []int32{
	8,  // 0: xqecz.RefreshRecommendRequest.items:type_name -> xqecz.RecommendItem
	9,  // 1: xqecz.RefreshRecommendResponse.results:type_name -> xqecz.ScoredItem
	12, // 2: xqecz.WorkerService.Health:input_type -> xqecz.HealthRequest
	0,  // 3: xqecz.WorkerService.GenerateThumbnail:input_type -> xqecz.ThumbnailRequest
	2,  // 4: xqecz.WorkerService.CompressImage:input_type -> xqecz.CompressRequest
	4,  // 5: xqecz.WorkerService.UploadToS3:input_type -> xqecz.UploadToS3Request
	6,  // 6: xqecz.WorkerService.FetchLinkPreview:input_type -> xqecz.LinkPreviewRequest
	10, // 7: xqecz.WorkerService.RefreshRecommend:input_type -> xqecz.RefreshRecommendRequest
	13, // 8: xqecz.WorkerService.Health:output_type -> xqecz.HealthResponse
	1,  // 9: xqecz.WorkerService.GenerateThumbnail:output_type -> xqecz.ThumbnailResponse
	3,  // 10: xqecz.WorkerService.CompressImage:output_type -> xqecz.CompressResponse
	5,  // 11: xqecz.WorkerService.UploadToS3:output_type -> xqecz.UploadToS3Response
	7,  // 12: xqecz.WorkerService.FetchLinkPreview:output_type -> xqecz.LinkPreviewResponse
	11, // 13: xqecz.WorkerService.RefreshRecommend:output_type -> xqecz.RefreshRecommendResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_xqecz_proto_init() }
func file_xqecz_proto_init() {
	if File_xqecz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xqecz_proto_rawDesc), len(file_xqecz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xqecz_proto_goTypes,
		DependencyIndexes: file_xqecz_proto_depIdxs,
		MessageInfos:      file_xqecz_proto_msgTypes,
	}.Build()
	File_xqecz_proto = out.File
	file_xqecz_proto_goTypes = nil
	file_xqecz_proto_depIdxs = nil
}
