/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AdminApiKeys: typeof import('./components/admin/AdminApiKeys.vue')['default']
    AdminClaimTable: typeof import('./components/admin/AdminClaimTable.vue')['default']
    AdminContentDrawer: typeof import('./components/admin/AdminContentDrawer.vue')['default']
    AdminContentTable: typeof import('./components/admin/AdminContentTable.vue')['default']
    AdminPollPanel: typeof import('./components/admin/AdminPollPanel.vue')['default']
    AdminReportTable: typeof import('./components/admin/AdminReportTable.vue')['default']
    AdminUploadPanel: typeof import('./components/admin/AdminUploadPanel.vue')['default']
    AdminUserTable: typeof import('./components/admin/AdminUserTable.vue')['default']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    ClaimModal: typeof import('./components/ClaimModal.vue')['default']
    CommentItem: typeof import('./components/CommentItem.vue')['default']
    CommentSections: typeof import('./components/CommentSections.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ContentMedia: typeof import('./components/ContentMedia.vue')['default']
    ContentSidebar: typeof import('./components/ContentSidebar.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    MarkdownToolbar: typeof import('./components/MarkdownToolbar.vue')['default']
    QuickUploadSheet: typeof import('./components/QuickUploadSheet.vue')['default']
    RecommendSection: typeof import('./components/RecommendSection.vue')['default']
    ReportModal: typeof import('./components/ReportModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeImage: typeof import('./components/SafeImage.vue')['default']
    TagCloud: typeof import('./components/admin/TagCloud.vue')['default']
    WaterfallCard: typeof import('./components/WaterfallCard.vue')['default']
  }
}
